SELECT 
    c1.TABLE_NAME AS ChildTable,
    c1.COLUMN_NAME AS ChildColumn,
    c2.TABLE_NAME AS ParentTable,
    c2.COLUMN_NAME AS ParentColumn
FROM 
    INFORMATION_SCHEMA.COLUMNS c1
JOIN 
    INFORMATION_SCHEMA.COLUMNS c2
    ON c1.COLUMN_NAME = c2.COLUMN_NAME
    AND c1.DATA_TYPE = c2.DATA_TYPE
    AND c1.TABLE_NAME <> c2.TABLE_NAME
LEFT JOIN 
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu
    ON c1.TABLE_NAME = kcu.TABLE_NAME 
    AND c1.COLUMN_NAME = kcu.COLUMN_NAME
LEFT JOIN 
    INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS rc
    ON kcu.CONSTRAINT_NAME = rc.CONSTRAINT_NAME
WHERE 
    rc.CONSTRAINT_NAME IS NULL
    AND c1.TABLE_SCHEMA = 'dbo' -- Adjust schema if necessary
    AND c2.TABLE_SCHEMA = 'dbo' -- Adjust schema if necessary
ORDER BY 
    c1.TABLE_NAME, c1.COLUMN_NAME;
